services:
  db:
    image: postgres:16-alpine
    container_name: tinyurl-db
    environment:
      POSTGRES_USER: tinyurl_admin        # ← new user
      POSTGRES_PASSWORD: tiny-tini-123    # ← new password
      POSTGRES_DB: tinyurl_db             # ← new database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tinyurl_admin -d tinyurl_db"]
      interval: 5s
      retries: 5  

  migrate:
    image: migrate/migrate:latest         # ← always pull the latest tag
    # platform: linux/amd64                # Apple Silicon: force amd64 layer
    depends_on:
      db:
        condition: service_healthy        # wait for DB to be ready
    volumes:
      - ./migrations:/migrations
    entrypoint: >
      migrate -path /migrations
              -database 'postgres://tinyurl_admin:tiny-tini-123@db:5432/tinyurl_db?sslmode=disable'
              up
    restart: "no"

volumes:
  db-data:
